### PR TITLE
Added chest shooting 

### LINKED ISSUE #8: Add physical bullets to machine gun
Currently firing the gun (press f) doesn't fire any bullets, so the gun doesn't damage enemies. We need to fire physical bullets; they can either be invisible (since they move "fast") or just small. If they are visible we need art for them.

### PR DESCRIPTION
**Pull request by frank731**

### CODE REVIEW

**Review by rpecka — DISMISSED** [review]
Please don’t include files from ‘.import’. You might need to merge master into your branch to get the update with the gitignore

**Review by jfdoming — COMMENTED** [review]
Could you post a gif or video of the changes? Generally when making a PR it's a good idea to give the reviewers some context.

**Comment by frank731** [comment]
https://drive.google.com/open?id=1mh5nMHf6zvxt22EW0B60x19naUbMSaGZ
clip of change

**Review by jfdoming — APPROVED** [review]
LGTM. We'll need to change the bullet art later though, so could you create a separate ticket for that?

**Pull request merged**
